language: java

jdk:
  - oraclejdk8

env:
  - NODE_VERSION="5.11"

before_install:
  - nvm install $NODE_VERSION
  - export CHROME_BIN=chromium-browser
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start

before_script:
  - ./gradlew stage

script:
  - ./gradlew check
