language: java

jdk:
  - oraclejdk8

env:
  - NODE_VERSION="5.11"

before_install:
  - nvm install $NODE_VERSION

before_script:
  - cd backend && ./gradlew stage
  - cd frontend && npm install

script:
  - cd backend && ./gradlew check
  - cd frontend && npm test
