language: java

jdk:
  - oraclejdk8

env:
  - NODE_VERSION="5.11"

before_install:
  - nvm install $NODE_VERSION

before_script:
  - ./gradlew stage
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start

script:
  - ./gradlew check
